[tool.poetry]
name = "sbank-client"
version = "0.1.0"
description = "Local implementation of the Sbank (processing) API client"
authors = []
packages = [{ include = "sbank_client" }]

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.7"
httpx = ">=0.27,<0.28"

[build-system]
requires = ["poetry-core>=1.8.1"]
build-backend = "poetry.core.masonry.api"
