from enum import StrEnum


class ErrorCodeEnum(StrEnum):
    """`error.errorCode` любого метода API NambaOne."""

    VALIDATION_ERROR = "VALIDATION_ERROR"
    MERCHANT_API_UNKNOWN_MERCHANT = "MERCHANT_API_UNKNOWN_MERCHANT"
    MERCHANT_API_NO_SALT = "MERCHANT_API_NO_SALT"
    MERCHANT_API_NO_SIGNATURE = "MERCHANT_API_NO_SIGNATURE"
    MERCHANT_API_WRONG_SIGNATURE = "MERCHANT_API_WRONG_SIGNATURE"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    MERCHANT_API_INVALID_EMPLOYEE_OR_BRANCH = "MERCHANT_API_INVALID_EMPLOYEE_OR_BRANCH"


class CreateRefundErrorCode(StrEnum):
    """`error.errorCode` метода "создать возврат" в дополнение к ErrorCodeEnum."""

    PAYMENT_ORDER_NOT_FOUND_EXCEPTION = "PAYMENT_ORDER_NOT_FOUND_EXCEPTION"
    REFUND_ORDERS_AMOUNT_IS_MORE_THAN_PARENT = "REFUND_ORDERS_AMOUNT_IS_MORE_THAN_PARENT"
    REFUND_PARENT_ORDER_WRONG_STATUS = "REFUND_PARENT_ORDER_WRONG_STATUS"
    WALLET_LIMIT_BALANCE_EXCEEDED_EXCEPTION = "WALLET_LIMIT_BALANCE_EXCEEDED_EXCEPTION"
    MERCHANT_ACCOUNT_LIMIT_BALANCE_EXCEEDED_EXCEPTION = "MERCHANT_ACCOUNT_LIMIT_BALANCE_EXCEEDED_EXCEPTION"
